### ISSUE TITLE
Better string handling in parser

### ISSUE THREAD

**Issue by divarvel** [Geal/proust#5]
Right now strings are parsed and encoded as a byte array. No extra validation is done, so byte arrays which don't represent strings can make it past the parsing phase.

**Comment by Geal** [comment]
`map_res!` and `str::from_utf8` should do the trick. It unwraps the `Result` if it is `Ok`.

**Comment by divarvel** [comment]
Done in 39f8e6f3b8e5dd3fc45eec8eaee5f84ae0a2b43f
